Allow ruby-head to fail
MSP-9923

ruby-head build is currently failing due to

```
undefined method `unpack' for nil:NilClass (NoMethodError)
/home/travis/.rvm/gems/ruby-head/gems/cucumber-1.3.16/lib/cucumber/ast/step.rb:81:in
`text_length'
```